name: Xe4 Workloads Pre PR Test
on:
  pull_request:
    paths:
      - "examples/sycl/xe4/**"
      - ".github/workflows/xe4_workloads_pre_pr.yml"
  workflow_dispatch:

env:
  HOME: /root

jobs:
  xe4_workloads_test:
    name: Xe4 Workloads Pre PR Test
    runs-on: [self-hosted, linux, gca_sim_docker]
    container:
      image: amr-registry.caas.intel.com/gca-sim-bkc/gen-isa:ww26
      volumes:
        - ${{ github.workspace }}/../../../creds:/root/creds
      credentials:
        username: ${{ secrets.DOCKER_REGISTRY_USR }}
        password: ${{ secrets.DOCKER_REGISTRY_PWD }}

    strategy:
      matrix:
        cfg: [genisa, xesim]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print last commit
        run: git log -1

      - name: Update credentials
        uses: intel-sandbox/containers.docker.gpu.compute.sim/.github/actions/update_creds@action_v1

      - name: Update Docker Image
        uses: intel-sandbox/containers.docker.gpu.compute.sim/.github/actions/update_img@action_v1
        with:
          # update_img is global flag, when it is false, it disalbed all other updates
          update_img: true
          print_version: true

          igc20_version: "main 4454"
          xesim_version: "XE3P_V2 98092 --snapshot"
          zesim_version: "main 20250724"

      - name: Build Xe4 workloads
        shell: bash
        run: |
          start_time=$(date +%s)

          cmake --preset xe4 2>&1 | tee build.log
          cmake --build --preset xe4 2>&1 | tee -a build.log

          exit_status=${{ '${PIPESTATUS[0]}' }}
          if [[ $exit_status -eq 124 ]]; then
            echo "Build timed out with exit code $exit_status." | tee -a $GITHUB_STEP_SUMMARY
          fi

          end_time=$(date +%s)
          elapsed_time=$((end_time - start_time))
          echo "Cmake build elapsed time: ${elapsed_time} seconds" | tee -a $GITHUB_STEP_SUMMARY

          exit $exit_status

      - name: Upload build log
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: "xe4_workloads_build.log"
          path: ./build.log
          retention-days: 14

      - name: Run Unit Test
        shell: bash
        run: |
          ctest --preset ${{ matrix.cfg }} --output-on-failure --timeout 2000 --output-junit "test_report.xml"

      - name: Publish Test Report
        uses: intel-sandbox/action-junit-report@v3
        continue-on-error: true
        with:
          check_name: "${{ matrix.cfg }} Report"
          detailed_summary: true
          include_passed: true
          require_passed_tests: true
          report_paths: "./build/test_report.xml"

      - name: Upload test log
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: "${{ inputs.cfg }}_test.log"
          path: ./build/Testing/Temporary/LastTest.log
          retention-days: 14

      - name: Delete unwantted files for artifacts
        continue-on-error: true
        shell: bash
        run: |
          # the name for ll dump file is too long that can't be extracted in windows
          find build/ -type f -iname "Dump.*.after*.ll" -exec rm -rf {} \;
          find build/ -type d -name "kernel_trace" -exec rm -rf {} \;
          # remove some large files in grits_data folder
          find build/ -type f -regex '.*grits_data.*buf\(in\|out\).*\(dat\|bin\)$' -exec rm -rf {} \;
          du build -sh

      - name: Upload the test Artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: "${{ inputs.cfg }}_test_artifact"
          path: ./build
          retention-days: 14
          include-hidden-files: true

      - name: Clean up
        continue-on-error: true
        run: |
          pwd
          git clean -xdf
          git submodule foreach --recursive git clean -xdf
